spring:
  profiles:
    active: local
  kafka:
    consumer:
      group-id: moebius-consumer-local

logging:
  level:
    root: INFO
    com.moebius: DEBUG
  file: /var/log/moebius/app.log

moebius:
  protocol: http
  host: 127.0.0.1
  web-security:
    all: /,
      /csrf,
      /static/**,
      /v2/api-docs,
      /swagger,
      /swagger-ui.html,
      /swagger-resources/**,
      /webjars/**,
      /member/**,
      /members/**,
      /login
    admin: /admin,
      /markets/**
    member: /stoplosses/**,
      /api-keys/**,
      /orders/**